export const SHOP_ROUTE = '/shop'
export const BASKET_ROUTE = '/basket'
export const OUR_SHOPS_ROUTE = '/ourShops'
export const CONTACTS_ROUTE = '/contacts'
export const WHOLE_SALERS_ROUTE = '/wholeSalers'